spring.application.name=my-first-spring-boot-app

# ========================
# DATABASE CONNECTION
# =======================
#Tell Spring WHERE your database is
spring.datasource.url=dbc:postgresql://localhost:5432/student_db

# Your PostgresSQL username (default is postgres)
spring.datasource.username=postgres

# Your PostgresSQL password (what you set during installation)
spring.datasource.password=root

# Your driver class (tells Spring which database type)
spring.datasource.driver.class.name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE SETTINGS
# ========================
# DDL Auto: What to do with tables when app starts
# "update"  = create tables if they don't exist, update if they do
# "create"  = DROP everything and recreate (loses data!)
# "none"    = Do nothing (you manage tables manually)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (great for learning!)
spring.jpa.show-sql=true

# Make SQL pretty in console
spring.jpa.properties.hibernate.format_sql=true

# Tell Hibernate we're using PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect
